import type { MetadataRoute } from "next";

// Makes the home-screen shortcut open as an app rather than a browser tab.
// Icons live in public/ and are regenerated by scripts/generate-icons.py.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Trade Journal",
    short_name: "Journal",
    description: "Private trade and fill tracking",
    start_url: "/",
    display: "standalone",
    background_color: "#12151c",
    theme_color: "#12151c",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
  };
}
