"""add_email_subject_body_to_fill

Revision ID: 84a8bf1dd0ab
Revises: 003
Create Date: 2026-04-18 02:43:23.063003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84a8bf1dd0ab'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fill', sa.Column('email_subject', sa.String(), nullable=True))
    op.add_column('fill', sa.Column('email_body_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fill', 'email_body_text')
    op.drop_column('fill', 'email_subject')
    # ### end Alembic commands ###
