# Copyright 2022 Webull
#
# Licensed under the Apache License, Version 2.0.
# Sourced from webull-openapi-python-sdk 2.0.8, file
#   webull/trade/events/events_pb2_grpc.py
# Modified only to update the relative import path to point at our
# local protobuf module. Redistributed under the Apache License 2.0;
# see backend/app/engine/webull_proto/NOTICE.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.engine.webull_proto import events_pb2 as events__pb2


class EventServiceStub(object):
    """gRPC trade event service — server-streaming Subscribe RPC."""

    def __init__(self, channel):
        self.Subscribe = channel.unary_stream(
            '/grpc.trade.event.EventService/Subscribe',
            request_serializer=events__pb2.SubscribeRequest.SerializeToString,
            response_deserializer=events__pb2.SubscribeResponse.FromString,
        )


class EventServiceServicer(object):
    """Server-side implementation. Not used in this project."""

    def Subscribe(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Subscribe': grpc.unary_stream_rpc_method_handler(
            servicer.Subscribe,
            request_deserializer=events__pb2.SubscribeRequest.FromString,
            response_serializer=events__pb2.SubscribeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'grpc.trade.event.EventService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
